// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGI_JMC.Models;

namespace SGI_JMC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220929002914_horarioservidor")]
    partial class horarioservidor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("SGI_JMC.Models.AcessoTipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NomeFuncionalidade")
                        .HasColumnName("NomeFuncionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("AcessoTipoUsuario");
                });

            modelBuilder.Entity("SGI_JMC.Models.Advertencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricaoDoFato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advertencia");
                });

            modelBuilder.Entity("SGI_JMC.Models.Declaracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Declaracao");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoProSic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("faseProSic")
                        .HasColumnType("int");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<int>("serieOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoProSic");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoSabadoLetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacaoSabado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataSabado")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracaoSabado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoSabadoLetivo");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaProSic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("faseProSic")
                        .HasColumnType("int");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<int>("serieOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaProSic");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaRegular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaRegular");
                });

            modelBuilder.Entity("SGI_JMC.Models.HorarioProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt05")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HorarioProfessor");
                });

            modelBuilder.Entity("SGI_JMC.Models.HorarioServidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnoHorario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HorarioServidor");
                });

            modelBuilder.Entity("SGI_JMC.Models.NotificacaoPendenciaDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdAulas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotificacaoPendenciaDiario");
                });

            modelBuilder.Entity("SGI_JMC.Models.OficioAssumiuFuncao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssumiuFuncao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroOficio")
                        .HasColumnType("int");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OficioAssumiuFuncao");
                });

            modelBuilder.Entity("SGI_JMC.Models.PerfilUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoUsuario");

                    b.HasIndex("UserId");

                    b.ToTable("PerfilUsuario");
                });

            modelBuilder.Entity("SGI_JMC.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeTipoUsuario")
                        .HasColumnName("NomeTipoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("SGI_JMC.Models.aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_folder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("SGI_JMC.Models.AcessoTipoUsuario", b =>
                {
                    b.HasOne("SGI_JMC.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SGI_JMC.Models.PerfilUsuario", b =>
                {
                    b.HasOne("SGI_JMC.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
