// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGI_JMC.Models;

namespace SGI_JMC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230318004122_novatabela")]
    partial class novatabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGI_JMC.Models.Advertencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("anoSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricaoDoFato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Advertencia");
                });

            modelBuilder.Entity("SGI_JMC.Models.AlunoAtual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorrecaoDeFluxo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("Transferido")
                        .HasColumnType("bit");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("AlunoAtual");
                });

            modelBuilder.Entity("SGI_JMC.Models.AlunoMatriculado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorrecaoDeFluxo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FaseProSic")
                        .HasColumnType("int");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerieOrigem")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<bool>("Transferido")
                        .HasColumnType("bit");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("AlunoMatriculado");
                });

            modelBuilder.Entity("SGI_JMC.Models.AlunoSemTransferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNasciimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EscolaAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemPendencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AlunoSemTransferencia");
                });

            modelBuilder.Entity("SGI_JMC.Models.Comunicado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataComparecimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembroEquipeDiretiva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comunicado");
                });

            modelBuilder.Entity("SGI_JMC.Models.Declaracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Declaracao");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoConcludentesProSic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaseProSic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDaMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDoPai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieDeOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoAutenticacaoConcludenteProSic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDeclaracaoConcludenteProSic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoConcludentesProSic");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoConcludentesRegular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("AnoSerie")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDaMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDoPai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("codigoAutenticacaoConcludente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDeclaracaoConcludente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoConcludentesRegular");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoDistanciaInteriorizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargaHorariaSemanal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeEntrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoAutenticacaoDeclaracaoInteriorizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distancia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InicioExercicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeclaracaoDistanciaInteriorizacao")
                        .HasColumnType("int");

                    b.Property<string>("OrgaoExpedidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turmas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoDistanciaInteriorizacao");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoExAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNasimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoExAluno");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoExServidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFimExercicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioExercicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoAutenticacaoExServidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDeclaracaoExServidor")
                        .HasColumnType("int");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoExServidor");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoGenerica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorpoDaDeclaracao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("codigoAutenticacaoDeclaracaoGenerica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDeclaracaoGenerica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoGenerica");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoProSic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("faseProSic")
                        .HasColumnType("int");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<int>("serieOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoProSic");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoResidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoAutenticacaoDeclaracaoResidencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDeclaracaoResidencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoResidencia");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoSabadoLetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoServidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnoDeTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacaoSabado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataSabado")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracaoSabado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoSabadoLetivo");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoServidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioExercicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoAutenticacaoServidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroDeclaracaoServidor")
                        .HasColumnType("int");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoServidor");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaProSic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("faseProSic")
                        .HasColumnType("int");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qtdFaltas")
                        .HasColumnType("int");

                    b.Property<int>("serieOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaProSic");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaProSicAnoFinalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerieSeguinte")
                        .HasColumnType("int");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("faseProsic")
                        .HasColumnType("int");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("turmaOrigem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaProSicAnoFinalizado");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaRegular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaRegular");
                });

            modelBuilder.Entity("SGI_JMC.Models.DeclaracaoTransferenciaRegularAnoFinalizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerieSeguinte")
                        .HasColumnType("int");

                    b.Property<int>("anoLetivo")
                        .HasColumnType("int");

                    b.Property<int>("anoSerie")
                        .HasColumnType("int");

                    b.Property<string>("codigoAutenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoSeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("numeroDeclaracao")
                        .HasColumnType("int");

                    b.Property<string>("numeroDoNis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("turma")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("DeclaracaoTransferenciaRegularAnoFinalizado");
                });

            modelBuilder.Entity("SGI_JMC.Models.HorarioApoioEscolar2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("CargaHorariaMensal")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt05")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HorarioApoioEscolar2");
                });

            modelBuilder.Entity("SGI_JMC.Models.HorarioProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("s05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sab01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sab02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sab03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sab04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sab05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("se05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tq05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tqu05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ts05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tsab01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tsab02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tsab03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tsab04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tsab05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tse05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tt05")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HorarioProfessor");
                });

            modelBuilder.Entity("SGI_JMC.Models.HorarioServidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurnoHorario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("domingo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quarta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quinta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sabado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segunda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sexta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("terca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HorarioServidor");
                });

            modelBuilder.Entity("SGI_JMC.Models.NotificacaoPendenciaDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataDeEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdAulas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotificacaoPendenciaDiario");
                });

            modelBuilder.Entity("SGI_JMC.Models.OficioAssumiuFuncao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CargoDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssumiuFuncao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FonteRecursos")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroOficio")
                        .HasColumnType("int");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OficioAssumiuFuncao");
                });

            modelBuilder.Entity("SGI_JMC.Models.OficioAssumiuFuncaoApoioEscolar2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("CargaHorariaMensal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssumiuFuncao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("FRC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroOficio")
                        .HasColumnType("int");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("disciplina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OficioAssumiuFuncaoApoioEscolar2");
                });

            modelBuilder.Entity("SGI_JMC.Models.OficioAssumiuFuncaoServidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("CargoDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CidadeDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAssumiuFuncao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FRC")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroOficio")
                        .HasColumnType("int");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vinculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OficioAssumiuFuncaoServidor");
                });

            modelBuilder.Entity("SGI_JMC.Models.OficioGeral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoDoDestinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorpoDoOficio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroOficio")
                        .HasColumnType("int");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destinatario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OficioGeral");
                });

            modelBuilder.Entity("SGI_JMC.Models.aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mother_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year_folder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
